### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Tester",
  "username": "Testing",
  "age": 1,
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Routine Index
get http://localhost:3000/routines.json

### Routine Create
post http://localhost:3000/routines
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0
Content-Type: application/json

{
"exercise_id": 2,
"workout_id": 2,
"added_weight": 10,
"reps": 10,
"sets": 3
}

### Routine Show
get http://localhost:3000/routines/4.json

### Routine Update
patch http://localhost:3000/routines/4
Content-Type: application/json

{
"exercise_id": 1,
"added_weight": 25,
"reps": 10
}

### Routine Delete
delete http://localhost:3000/routines/12



### Workouts Index
get http://localhost:3000/workouts.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0

### Workouts Show
get http://localhost:3000/workouts/1.json

### Workouts Create
post http://localhost:3000/workouts
Content-Type: application/json

{
"title": "Test"
}

### Workouts Update
patch http://localhost:3000/workouts/1.json

{
"title": "Arms day!"
}

### Exercise Index
get http://localhost:3000/exercises.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0

### Exercise Show
get http://localhost:3000/exercises/1.json



### User_Equipment Create
POST http://localhost:3000/userequipment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0
Content-Type: application/json

{
  "id": 4
}

### User_Equipment Delete
DELETE http://localhost:3000/userequipment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0



### Equipment Index
get http://localhost:3000/equipment.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0


### User Vote Index
get http://localhost:3000/votes.json

### User Vote Show
get http://localhost:3000/votes/4
Content-Type: application/json

{
  "workout_id": 4
}

### User Vote Create
post http://localhost:3000/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0
Content-Type: application/json

{
  "workout_id": 4,
  "vote": true
}

### User Vote Update
patch http://localhost:3000/votes/15
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0
Content-Type: application/json

{
  "vote": false
}


### User Vote Delete
delete http://localhost:3000/votes/1



### Workout Favorite Index
get http://localhost:3000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0

### Workout Favorite Create
post http://localhost:3000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0
Content-Type: application/json

{
  "workout_id": 3
}

### Workout Favorite Delete
delete http://localhost:3000/favorites/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjU4NDMzODR9.JbHGeMOhCmAsPkMfe97YENNtPHMX5a8SlqrnEuFDDB0