### Workout Exercises Index
get http://localhost:3000/routines.json

### Workout Exercises Create
post http://localhost:3000/routines
Content-Type: application/json

{
"exercise_id": 2,
"workout_id": 2,
"added_weight": 10,
"reps": 10,
"sets": 3
}

### Workout Exercises Update
patch http://localhost:3000/routines/4
Content-Type: application/json

{
"exercise_id": 1,
"added_weight": 25,
"reps": 10
}



### Workouts (routines at the moment) Index
get http://localhost:3000/workouts.json

### Workouts (routines at the moment) Create
post http://localhost:3000/workouts
Content-Type: application/json

{
"title": "Arms day!"
}