###
get http://localhost:3000/workouts

###
post http://localhost:3000/workouts
Content-Type: application/json

{
"exercise_id": 2,
"workout_id": 2,
"added_weight": 10,
"reps": 10,
"sets": 3
}

###
patch http://localhost:3000/workouts/4
Content-Type: application/json

{
"exercise_id": 1,
"added_weight": 25,
"reps": 10
}